### ISSUE TITLE
Deasync Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by jordiblanchcarles** [senzil/cec-monitor#15]
Hello,

I'm trying to use cec-monitor within an ElectronJS v5.0.2 app, but the app is not starting because it throws an error while loading deasync module. Here it is the error thrown:

*App threw an error during load
Error: Could not locate the bindings file. Tried:
 → /home/pi/cityadpro_player/node_modules/deasync/build/deasync.node
 → /home/pi/cityadpro_player/node_modules/deasync/build/Debug/deasync.node
 → /home/pi/cityadpro_player/node_modules/deasync/build/Release/deasync.node
 → /home/pi/cityadpro_player/node_modules/deasync/out/Debug/deasync.node
 → /home/pi/cityadpro_player/node_modules/deasync/Debug/deasync.node
 → /home/pi/cityadpro_player/node_modules/deasync/out/Release/deasync.node
 → /home/pi/cityadpro_player/node_modules/deasync/Release/deasync.node
 → /home/pi/cityadpro_player/node_modules/deasync/build/default/deasync.node
 → /home/pi/cityadpro_player/node_modules/deasync/compiled/12.0.0/linux/arm/deasync.node
    at bindings (/home/pi/cityadpro_player/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/cityadpro_player/node_modules/deasync/index.js:30:31)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/pi/cityadpro_player/node_modules/@senzil/cec-monitor/lib/cec-monitor.js:17:39)*

Does anybody have any clue about how to solve this problem?

Thank you!

**Comment by pablodgonzalez** [comment]
Deasync bindings are specific for the OS. So, It could be an issue with the Deasync version or maybe Deasync is not compatible with your OS. You should go to Deasync repo and check there or open an issue.

**Comment by jordiblanchcarles** [comment]
It looks like ElectronJS and Deasync are not compatible. Is there any way to avoid using Deasync in cec-monitor?

**Comment by pablodgonzalez** [comment]
Fork the library, remove de dependency and the functions where it is used.

**Comment by jordiblanchcarles** [comment]
Hello, I've already replaced the Deasync.loopWhile() method you were using with [p-wait-for](https://www.npmjs.com/package/p-wait-for) module's pWaitFor method to avoid deasync module, and it seems to be working properly.

Would you like to commit these changes?

**Comment by pablodgonzalez** [comment]
Thanks @jordiblanchcarles We will check the changes and make performances test. By the way, in the future the main idea is make and node library to support the libcec without wrap the cec-client CLI because it is only for debugging and test.
Personally I don't know how to work ElectronJS with the bindinds.
I hope to make the tests soon.
